### PR TITLE
Some massive UI fixes :)

### PR DESCRIPTION
**Pull request by k-poole**
Okay I've changed HEAPS of files in this, but it's all tested and there's some screenshots attached too.

The point was primarily to update the theme to look/feel like WHM 11, and seem more professional by have consistent font and showing all names correctly as "Let's Encrypt".

I also changed a few small wordings to make it more clearer and in-line with cPanel wording that's used.

Lastly, I fixed up the WHM icon, which used to be SVG, and I added a CHANGELOG with my details in it.

Hopefully everyone likes it :) See attached pics for live example. Cheers

le_4

le_1

le_2

le_3

### CODE REVIEW

**Comment by W5x** [comment]
great, thank you

how to apply that fix , i tried to upgrade and install again and nothing changed 

do i have to wait for the next release ?

**Comment by k-poole** [comment]
> Hi W5x

You  can either pull my branch or wait for Prajithp to merge and then do
another 'git pull && ./install.sh' on your local copy. If you're not using
git then just download the zip, extract and run install.sh :)

-KP

## 

Kind regards,
Keith Poole | Managing Director
Agilis IT Australia

**Comment by W5x** [comment]
i tried this codes with no luck 

cd letsencrypt-cpanel
/usr/local/cpanel/3rdparty/bin/git pull
./upgrade.sh

and 

/usr/local/cpanel/3rdparty/bin/git clone https://github.com/Prajithp/letsencrypt-cpanel.git
cd letsencrypt-cpanel
./install.sh

the result is the same , could you correct me how to ?

thanks in advance

**Comment by k-poole** [comment]
Hi

You have to wait for Prajithp to accept my pull request before that will
work.

If you want you can download ZIP from my wording-fixes branch, unzip and
run ./install.sh from there :)

-KP

## 

Kind regards,
Keith Poole | Managing Director
Agilis IT Australia

**Comment by W5x** [comment]
aha OK, thank you.

**Comment by WilliamIsted** [comment]
Yey! A consistent UI makes for happy users. Thanks for the update.

**Comment by Prajithp** [comment]
Woww Thank you so much again :)

**Comment by k-poole** [comment]
@Prajithp ; Not a problem mate I'm glad you're happy with the changes.

@WilliamIsted ; Any time.

@W5x ; You should be fine to do `git pull && ./install.sh` now :)

## 

Kind regards,
Keith Poole | Managing Director
Agilis IT Australia

**Comment by k-poole** [comment]
Hi.

The PR is merged. Git pull and ./install.sh should now work :)

-KP


-- 
Kind regards,
Keith Poole | Managing Director
Agilis IT Australia

**Comment by k-poole** [comment]
No worries happy to help :)

-KP


-- 
Kind regards,
Keith Poole | Managing Director
Agilis IT Australia

**Pull request merged**
